<logs><log LogGUID="699f35fe-e389-4f23-917a-5a618e2ea699" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="0" LogPortalName="MD529" LogCreateDate="2/9/2021 6:17:23 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="DESKTOP-585QGBN" LogConfigID="4"><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/Default.aspx</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>2bd92557-38ee-4aa6-930d-2901d0d58d76</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>yqhprvxE9nFG5m3QmvDd1qaHKlM=</ExceptionHash><Message>Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Security.Membership.AspNetMembershipProvider.GetUserByUserNameFromDataStore(Int32 portalId, String username)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromRuntimeCache(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage /><InnerStackTrace /><Source>System.Data</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="17da3c3a-7ca0-4c0d-b115-d100d3b76cd4" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="0" LogPortalName="MD529" LogCreateDate="2/9/2021 6:18:31 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="DESKTOP-585QGBN" LogConfigID="4"><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/Default.aspx</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>7e3438fa-cdcc-4c9c-b334-7ccbfce740a8</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>ijAv5g7UvIHnRDqi9NREa11C/Kg=</ExceptionHash><Message>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)</Message><StackTrace>   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Security.Membership.AspNetMembershipProvider.GetUserByUserNameFromDataStore(Int32 portalId, String username)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromRuntimeCache(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="63549f99-987f-4579-937d-120125162f60" LogFileID="" LogTypeKey="CACHE_REMOVED" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/10/2021 10:56:07 AM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="DESKTOP-585QGBN" LogConfigID=""><LogProperties><LogProperty><PropertyName>DNN_GetLogTypeConfigInfoByKey</PropertyName><PropertyValue>Removed</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="fbffa043-580c-4089-b36d-d06406498be4" LogFileID="" LogTypeKey="CACHE_REMOVED" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/10/2021 10:56:22 AM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="DESKTOP-585QGBN" LogConfigID=""><LogProperties><LogProperty><PropertyName>DNN_Folders0</PropertyName><PropertyValue>Removed</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="ba2bf5b1-781f-4517-a6f5-5f2ae948218f" LogFileID="" LogTypeKey="CACHE_REMOVED" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/10/2021 10:56:37 AM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="DESKTOP-585QGBN" LogConfigID=""><LogProperties><LogProperty><PropertyName>DNN_url_ParameterRedirectActions_0</PropertyName><PropertyValue>Removed</PropertyValue></LogProperty></LogProperties></log></logs>
